### ISSUE TITLE
Suggestion add Operator+

### ISSUE THREAD

**Issue by seppy87** [VinGarcia/Simple-Iterator-Template#10]
Dear Coder,
I am using your Code for iterators. 

Any suggestion how to implement operator+ in your code?

**Comment by VinGarcia** [comment]
Use TDD: First create a test on tests.cpp using the operator +, e.g.:

```
ASSERT(m_it+2 == ((m_it++)++)
```

Then write a code to add this operator. Use the implementation of the ++ operation as a base then modify it for working with +.

Some tips that hopefully can help you:

1. One thing that is not obvious about C++ templates is that it attempts to create a valid implementation with all functions that are actually used. What it means is that all instantiations of this template depend on the struct `it_state`, if some function is not implemented there but it is not being used (e.g. the prev() method is not implemented), there is no problem, it will compile correctly. It will only give you a compile error if you are trying to use the operator+ on an iterator whose `it_state` doesn't have the function required by this implementation.

2. Another tip: Make your change on all 4 templates, since each of them works for a different situation, it would be nice if your testes covered all 4 cases.

Finally, if your tests are passing you can submit a PR, but I have to warn you I am currently very slow on reviewing PRs, so please be patient with me.
