### ISSUE TITLE
Macro naming convention

### ISSUE THREAD

**Issue by heyx3** [VinGarcia/Simple-Iterator-Template#11]
It might be a good idea to rename the macros to something more explicit to prevent potential name collisions. In particular, I feel like macros named "SETUP_[X]" could quite easily collide with someone's code.

I suggest adding a clear prefix to them, like "VGSI" or "SIMPLE_ITERATOR".

**Comment by VinGarcia** [comment]
Yep that's true. I mean most of the macros have the word "ITERATOR" in it, so it would be unlikely that someone would use this library and at the same time define macros for setting up iterators, but at least one of the macros doesn't this word which might be problematic, namely the `STL_TYPEDEFS` macro.

I am not sure I should be worried about backwards compatibility, since people are unlikely to update this package from time to time, but maybe if I just updated this `STL_TYPEDEFS` to something like `STL_ITERATOR_TYPEDEFS` maybe this would already be safe enough, what do you think?

**Comment by heyx3** [comment]
If you're worried about backwards compatibility, you could go ahead and change the macros, then also define the old version of those names **if** they aren't defined already.

Or, let the users manually enable the legacy names by #defining a special token.

**Comment by VinGarcia** [comment]
Good idea @heyx3, what do you think of this PR:

https://github.com/VinGarcia/Simple-Iterator-Template/pull/13

**Comment by VinGarcia** [comment]
Uhm, I see I should also add some guards if the macros are already defined.., I will add them too.

**Comment by VinGarcia** [comment]
Done =]

**Comment by VinGarcia** [comment]
Just merged PR #13, so I will close this one =]
