### ISSUE TITLE
Incorrect call to a cmd() function?

### ISSUE THREAD

**Issue by JeanPhilippeLebel** [VinGarcia/Simple-Iterator-Template#16]
Hello, 

The following lines call a cmd() function which is not defined. It think the correct call should be to the equal function instead.

https://github.com/VinGarcia/Simple-Iterator-Template/blob/a9baefaeb5a941475e814f4e5aa298c9ceda2ecc/iterator_tpl.h#L191
https://github.com/VinGarcia/Simple-Iterator-Template/blob/a9baefaeb5a941475e814f4e5aa298c9ceda2ecc/iterator_tpl.h#L261

If the author can confirm this is indeed and error, I can propose a patch.

Thanks

**Comment by VinGarcia** [comment]
Oh indeed, I am surprised it is there 🤔 

I believe we'll need to replace `cmd` for `!equals`, and thanks for reporting.

**Comment by VinGarcia** [comment]
I am also overdue to update the example files, if you have time and want to fix it, it would be great =]

**Comment by VinGarcia** [comment]
Thanks @JeanPhilippeLebel, just merged your PR.

I also took the time to fix the examples, they are now all working with the `equals()` function instead of the `cmp()`

One curiosity: This bug you found was actually here since the beginning, I think you are the first person to actually use that particular implementation, or at least to bother commenting on it, I should write some actual tests for it later. But finding time for this is hard.

Thanks again, I will close this issue for now.
